package com.romullogirardi.checker.view;

import java.util.ArrayList;
import java.util.List;

import com.romullogirardi.checker.model.Enums.Discipline;
import com.romullogirardi.checker.model.Enums.ForeignLanguage;
import com.romullogirardi.checker.model.Enums.KnowledgeArea;
import com.romullogirardi.checker.model.Enums.QuestionOptionLetters;
import com.romullogirardi.checker.model.Question;
import com.romullogirardi.checker.model.QuestionsChecker;

public class CheckerTest {

	public static void main(String[] args) {
		
		//Setting student name and foreign language
		QuestionsChecker.getInstance().setStudentName("Lucas Perez de Souza");
		QuestionsChecker.getInstance().setForeignLanguage(ForeignLanguage.SPANISH);
		
		//Setting questions
		List<Question> questions = initializeQuestions();
		QuestionsChecker.getInstance().setQuestions(questions);
		
		//Setting selected options
		List<QuestionOptionLetters> selectedOptions = initializeSelectedOptions();
		QuestionsChecker.getInstance().setSelectedOptions(selectedOptions);
		
		//Showing result
		QuestionsChecker.getInstance().showResult();
	}

	private static  List<Question> initializeQuestions() {
		
		List<Question> questions = new ArrayList<Question>();
		//Ciências Humanas e suas Tecnologias - 1 a 45
		/*1*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*2*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*3*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*4*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*5*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*6*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*7*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*8*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*9*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*10*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*11*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*12*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*13*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*14*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*15*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*16*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*17*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*18*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*19*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*20*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*21*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*22*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*23*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*24*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*25*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*26*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*27*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*28*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*29*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*30*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*31*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*32*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*33*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*34*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.B));
		/*35*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*36*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*37*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*38*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*39*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.E));
		/*40*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*41*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*42*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.A));
		/*43*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		/*44*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.C));
		/*45*/questions.add(new Question(KnowledgeArea.HUMAN_SCIENCE, Discipline.HUMAN_SCIENCE, QuestionOptionLetters.D));
		//Ciências da Natureza e suas Tecnologias - 46 a 90
		/*46*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*47*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*48*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*49*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*50*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*51*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*52*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*53*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*54*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*55*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*56*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*57*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*58*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*59*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*60*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*61*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*62*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*63*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*64*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*65*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*66*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*67*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*68*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*69*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*70*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*71*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*72*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*73*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*74*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*75*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*76*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*77*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		/*78*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*79*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*80*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*81*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*82*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*83*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*84*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*85*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.A));
		/*86*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*87*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.B));
		/*88*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.E));
		/*89*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.C));
		/*90*/questions.add(new Question(KnowledgeArea.NATURAL_SCIENCE, Discipline.NATURAL_SCIENCE, QuestionOptionLetters.D));
		//Linguagens e suas Tecnologias - 91 a 135
		if(QuestionsChecker.getInstance().getForeignLanguage().equals(ForeignLanguage.ENGLISH)) {
			/*91*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
			/*92*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
			/*93*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
			/*94*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
			/*95*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		}
		else {
			/*91*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
			/*92*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
			/*93*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
			/*94*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
			/*95*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		}
		/*96*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*97*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*98*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*99*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*100*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*101*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*102*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*103*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*104*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*105*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*106*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*107*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*108*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*109*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*110*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*111*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*112*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*113*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*114*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*115*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*116*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*117*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*118*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*119*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*120*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*121*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*122*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*123*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*124*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*125*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*126*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*127*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.C));
		/*128*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*129*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.A));
		/*130*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*131*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*132*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		/*133*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.D));
		/*134*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.B));
		/*135*/questions.add(new Question(KnowledgeArea.LANGUAGES, Discipline.LANGUAGES, QuestionOptionLetters.E));
		//Matemática e suas Tecnologias - 136 a 180
		/*136*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*137*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*138*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*139*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*140*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*141*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*142*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		/*143*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*144*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*145*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*146*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*147*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*148*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*149*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*150*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*151*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		/*152*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*153*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*154*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*155*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*156*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		/*157*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*158*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*159*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*160*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		/*161*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*162*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*163*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*164*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*165*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*166*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*167*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*168*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		/*169*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*170*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*171*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*172*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*173*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*174*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.C));
		/*175*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*176*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.B));
		/*177*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*178*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.A));
		/*179*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.D));
		/*180*/questions.add(new Question(KnowledgeArea.MATHEMATICS, Discipline.MATHEMATICS, QuestionOptionLetters.E));
		return questions;
	}
	
	private static List<QuestionOptionLetters> initializeSelectedOptions() {
		
		List<QuestionOptionLetters> selectedOptions = new ArrayList<QuestionOptionLetters>();
		//Ciências Humanas e suas Tecnologias - 1 a 45
		/*1*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*2*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*3*/selectedOptions.add(QuestionOptionLetters.E);
		/*4*/selectedOptions.add(QuestionOptionLetters.D);
		/*5*/selectedOptions.add(QuestionOptionLetters.C);
		/*6*/selectedOptions.add(QuestionOptionLetters.D);
		/*7*/selectedOptions.add(QuestionOptionLetters.E);
		/*8*/selectedOptions.add(QuestionOptionLetters.D);
		/*9*/selectedOptions.add(QuestionOptionLetters.E);
		/*10*/selectedOptions.add(QuestionOptionLetters.C);
		/*11*/selectedOptions.add(QuestionOptionLetters.A);
		/*12*/selectedOptions.add(QuestionOptionLetters.A);
		/*13*/selectedOptions.add(QuestionOptionLetters.E);
		/*14*/selectedOptions.add(QuestionOptionLetters.C);
		/*15*/selectedOptions.add(QuestionOptionLetters.E);
		/*16*/selectedOptions.add(QuestionOptionLetters.A);
		/*17*/selectedOptions.add(QuestionOptionLetters.C);
		/*18*/selectedOptions.add(QuestionOptionLetters.A);
		/*19*/selectedOptions.add(QuestionOptionLetters.D);
		/*20*/selectedOptions.add(QuestionOptionLetters.C);
		/*21*/selectedOptions.add(QuestionOptionLetters.D);
		/*22*/selectedOptions.add(QuestionOptionLetters.D);
		/*23*/selectedOptions.add(QuestionOptionLetters.C);
		/*24*/selectedOptions.add(QuestionOptionLetters.B);
		/*25*/selectedOptions.add(QuestionOptionLetters.A);
		/*26*/selectedOptions.add(QuestionOptionLetters.E);
		/*27*/selectedOptions.add(QuestionOptionLetters.A);
		/*28*/selectedOptions.add(QuestionOptionLetters.A);
		/*29*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*30*/selectedOptions.add(QuestionOptionLetters.E);
		/*31*/selectedOptions.add(QuestionOptionLetters.B);
		/*32*/selectedOptions.add(QuestionOptionLetters.A);
		/*33*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*34*/selectedOptions.add(QuestionOptionLetters.B);
		/*35*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*36*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*37*/selectedOptions.add(QuestionOptionLetters.C);
		/*38*/selectedOptions.add(QuestionOptionLetters.B);
		/*39*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*40*/selectedOptions.add(QuestionOptionLetters.A);
		/*41*/selectedOptions.add(QuestionOptionLetters.A);
		/*42*/selectedOptions.add(QuestionOptionLetters.A);
		/*43*/selectedOptions.add(QuestionOptionLetters.C);
		/*44*/selectedOptions.add(QuestionOptionLetters.B);
		/*45*/selectedOptions.add(QuestionOptionLetters.D);
		//Ciências da Natureza e suas Tecnologias - 46 a 90
		/*46*/selectedOptions.add(QuestionOptionLetters.B);
		/*47*/selectedOptions.add(QuestionOptionLetters.E);
		/*48*/selectedOptions.add(QuestionOptionLetters.E);
		/*49*/selectedOptions.add(QuestionOptionLetters.B);
		/*50*/selectedOptions.add(QuestionOptionLetters.D);
		/*51*/selectedOptions.add(QuestionOptionLetters.C);
		/*52*/selectedOptions.add(QuestionOptionLetters.C);
		/*53*/selectedOptions.add(QuestionOptionLetters.E);
		/*54*/selectedOptions.add(QuestionOptionLetters.B);
		/*55*/selectedOptions.add(QuestionOptionLetters.A);
		/*56*/selectedOptions.add(QuestionOptionLetters.B);
		/*57*/selectedOptions.add(QuestionOptionLetters.C);
		/*58*/selectedOptions.add(QuestionOptionLetters.D);
		/*59*/selectedOptions.add(QuestionOptionLetters.A);
		/*60*/selectedOptions.add(QuestionOptionLetters.B);
		/*61*/selectedOptions.add(QuestionOptionLetters.B);
		/*62*/selectedOptions.add(QuestionOptionLetters.E);
		/*63*/selectedOptions.add(QuestionOptionLetters.A);
		/*64*/selectedOptions.add(QuestionOptionLetters.D);
		/*65*/selectedOptions.add(QuestionOptionLetters.D);
		/*66*/selectedOptions.add(QuestionOptionLetters.E);
		/*67*/selectedOptions.add(QuestionOptionLetters.B);
		/*68*/selectedOptions.add(QuestionOptionLetters.E);
		/*69*/selectedOptions.add(QuestionOptionLetters.C);
		/*70*/selectedOptions.add(QuestionOptionLetters.A);
		/*71*/selectedOptions.add(QuestionOptionLetters.D);
		/*72*/selectedOptions.add(QuestionOptionLetters.C);
		/*73*/selectedOptions.add(QuestionOptionLetters.D);
		/*74*/selectedOptions.add(QuestionOptionLetters.A);
		/*75*/selectedOptions.add(QuestionOptionLetters.E);
		/*76*/selectedOptions.add(QuestionOptionLetters.C);
		/*77*/selectedOptions.add(QuestionOptionLetters.E);
		/*78*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*79*/selectedOptions.add(QuestionOptionLetters.B);
		/*80*/selectedOptions.add(QuestionOptionLetters.E);
		/*81*/selectedOptions.add(QuestionOptionLetters.D);
		/*82*/selectedOptions.add(QuestionOptionLetters.C);
		/*83*/selectedOptions.add(QuestionOptionLetters.A);
		/*84*/selectedOptions.add(QuestionOptionLetters.B);
		/*85*/selectedOptions.add(QuestionOptionLetters.B);
		/*86*/selectedOptions.add(QuestionOptionLetters.D);
		/*87*/selectedOptions.add(QuestionOptionLetters.C);
		/*88*/selectedOptions.add(QuestionOptionLetters.D);
		/*89*/selectedOptions.add(QuestionOptionLetters.B);
		/*90*/selectedOptions.add(QuestionOptionLetters.A);
		//Linguagens e suas Tecnologias - 91 a 135
		/*91*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*92*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*93*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*94*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*95*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*96*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*97*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*98*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*99*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*100*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*101*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*102*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*103*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*104*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*105*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*106*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*107*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*108*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*109*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*110*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*111*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*112*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*113*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*114*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*115*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*116*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*117*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*118*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*119*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*120*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*121*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*122*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*123*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*124*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*125*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*126*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*127*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*128*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*129*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*130*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*131*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*132*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*133*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*134*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*135*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		//Matematica e suas Tecnologias - 136 a 180
		/*136*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*137*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*138*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*139*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*140*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*141*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*142*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*143*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*144*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*145*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*146*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*147*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*148*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*149*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*150*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*151*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*152*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*153*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*154*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*155*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*156*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*157*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*158*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*159*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*160*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*161*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*162*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*163*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*164*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*165*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*166*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*167*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*168*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*169*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*170*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*171*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*172*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*173*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*174*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*175*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*176*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*177*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*178*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*179*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		/*180*/selectedOptions.add(QuestionOptionLetters.VAZIA);
		return selectedOptions;
	}
}